kind: Deployment
apiVersion: apps/v1
metadata:
  name: opencloud
  namespace: cloud
  annotations:
    configmap.reloader.stakater.com/reload: "opencloud-config"
    secret.reloader.stakater.com/reload: "opencloud-env"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencloud
      component: opencloud
  template:
    metadata:
      labels:
        app: opencloud
        component: opencloud
    spec:
      containers:
        - name: opencloud
          image: opencloudeu/opencloud-rolling:latest
          envFrom:
            - secretRef:
                name: opencloud-env
          # TODO
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 512Mi
          ports:
            - name: grpc
              containerPort: 9142
            - name: http
              containerPort: 9200
            - name: metrics
              containerPort: 9201
            - name: nats
              containerPort: 9233
          volumeMounts:
            - name: apps
              mountPath: /var/lib/opencloud/web/assets/apps
            - name: config
              mountPath: /etc/opencloud
            - name: data
              mountPath: /var/lib/opencloud
            - name: antivirus
              mountPath: /var/run/clamav
            - name: config-files
              mountPath: /etc/opencloud/banned-password-list.txt
              subPath: banned-password-list.txt
            - name: config-files
              mountPath: /etc/opencloud/csp.yaml
              subPath: csp.yaml
            - name: config-files
              mountPath: /etc/opencloud/proxy.yaml
              subPath: proxy.yaml
      volumes:
        - name: apps
          persistentVolumeClaim:
            claimName: opencloud-apps
        - name: config
          persistentVolumeClaim:
            claimName: opencloud-config
        - name: data
          persistentVolumeClaim:
            claimName: opencloud-data
        - name: antivirus
          persistentVolumeClaim:
            claimName: clamav-socket
        - name: config-files
          configMap:
            name: opencloud-config