apiVersion: v1
kind: Service
metadata:
  name: opencloud
  namespace: cloud
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/path: /metrics
    prometheus.io/port: "9201"
spec:
  type: ClusterIP
  selector:
    app: opencloud
    component: wopi
  ports:
    - name: grpc
      port: 9142
      targetPort: 9142
    - name: http
      port: 9200
      targetPort: 9200
    - name: metrics
      port: 9201
      targetPort: 9201
    - name: nats
      port: 9233
      targetPort: 9233