kind: Deployment
apiVersion: apps/v1
metadata:
  name: authelia
  namespace: users
  annotations:
    secret.reloader.stakater.com/reload: "authelia-config,authelia-keys"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      enableServiceLinks: false # Required as per https://www.authelia.com/integration/kubernetes/introduction/
      priorityClassName: system-cluster-critical
      containers:
        - name: authelia
          image: authelia/authelia:latest
          env:
            - name: TZ
              value: Europe/London
            - name: X_AUTHELIA_CONFIG_FILTERS
              value: template
            - name: X_AUTHELIA_CONFIG
              value: /config/configuration.yaml
          ports:
            - name: http
              containerPort: 9091
            - name: metrics
              containerPort: 9959
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
            - name: keys
              mountPath: /keys/rsa.key
              subPath: rsa.key
      volumes:
        - name: config
          secret:
            secretName: authelia-config
            items:
              - key: configuration.yaml
                path: configuration.yaml
        - name: keys
          secret:
            secretName: authelia-keys
            items:
              - key: rsa.key
                path: rsa.key