apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: users
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/path: /metrics
    prometheus.io/port: "9959"
spec:
  selector:
    app: authelia
  type: ClusterIP
  ports:
    - name: http
      port: 9091
      targetPort: 9091
    - name: metrics
      port: 9959
      targetPort: 9959