apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nocodb
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - db.starsystem.dev
      secretName: nocodb-tls
  rules:
    - host: db.starsystem.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nocodb
                port:
                  number: 8080