kind: Deployment
apiVersion: apps/v1
metadata:
  name: radicale
  namespace: cloud
  annotations:
    configmap.reloader.stakater.com/reload: "radicale-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencloud
      component: radicale
  template:
    metadata:
      labels:
        app: opencloud
        component: radicale
    spec:
      containers:
        - name: radicale
          image: opencloudeu/radicale
          ports:
            - name: http
              containerPort: 5232
          # TODO
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /etc/radicale
              subPath: config
            - name: data
              mountPath: /var/lib/radicale
      volumes:
        - name: config
          configMap:
            name: radicale-config
        - name: data
          persistentVolumeClaim:
            claimName: radicale-data