---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-config
  namespace: redis-cluster
spec:
  encryptedData:
    redis.conf: AgANtXLcVt4upuBcI/Le64s1bLZyRndOLEvpxKJfX774TalHnn7SbjsmRCfCWfRDUo5RkuWA1iHKkdubASl95ISwp2WBC+A9uJ1T1hAVLNcvj+aOoPqGDLld1fbKOKwJxdXRmXjrRrvIOGNSc1WmBMBZsaFostzYWxEAeiQ8qPJEp2QrKZMWzjWzLI7ngbsWC45QUig1ypurvONgf2FkHNS2A/LziEewB/lPko336rvEtYIkwewuqQ9PfnxbUmiXVNaeIZYhM0UvYAUu7xMJ5ICTSrLcLPHCWxTnC5fdpkvZMV6OEDmz1trxYyW3/OCVK2LiMJCglLapiTgtkYp8j2Ieq28Lh7UREb4TXAeuls1wynNJth9ukb92YgO624XyU7vt62mhm1fQwClZWNJxaMByz1HoaT9jsSDkxkqHyoZD9gztuk2jYdzLPKZZuNNao+VJs1CAxoqyPnh6gMH44eKYu+8EtPOjV0pNezqr0VK/uZsTQ48cNgfSPgS1yLJu8LRMbbnIL2gOwkoLNV+vbtg65icSpx5DhoIfVG3ohEitkLUuhtgUtbPPqA/3YDQBEM6p3iJkig7wJmrDZBrfNjqlwTGDTV23eXbahTDr4aPW7T74EUqoMkj0FKg0JOwBIpuCimRw3sWbTo7N6/pRMxJuD2hXWcfLpsEI2kAHkBMoKhsO2YLulm+TuRjpiDd6rZsYe/UBfOhnk/az5r8y45GwlEAhhhkj/H4U0dBi1iC5O3WsFAGjsJ5eFNba+ef+8pNItF2yDE0W39Sn7QmhY55CZIiyvnsVaoWgSZgQVXG1s3FMxrNAE1QI3WLi2jLYX428Cd1YKGbXERSlFRMgeYBJ4G/U93yH/j2YECSh0HCQKFc0xscmvGruHyDObeKgRL8JaBsHTv5S+VKoCdUClxAypubEAusQuqEoKh+t3hMXac3iZyjx4KHCA09G198aRQddMv7U
  template:
    metadata:
      creationTimestamp: null
      name: redis-config
      namespace: redis-cluster
