apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-cluster
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    cluster-enabled yes
    save 300 100
    aclfile /usr/local/etc/acl/users.conf