kind: Deployment
apiVersion: apps/v1
metadata:
  name: lldap
  namespace: users
  annotations:
    secret.reloader.stakater.com/reload: "lldap-env"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      priorityClassName: system-cluster-critical
      containers:
        - name: lldap
          image: lldap/lldap:stable
          envFrom:
            - secretRef:
                name: lldap-env
          ports:
            - name: http
              containerPort: 17170
            - name: ldap
              containerPort: 3890
            - name: ldaps
              containerPort: 6360
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              memory: 100Mi