apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - service-account.yml
  - cluster-role.yml
  - cluster-role-binding.yml
  - crds.yml
  - basic-auth.yml
  - middleware-basic-auth.yml
  - middleware-cors.yml
  - middleware-vpn-only.yml
  - middleware-forward-auth.yml
  - daemonset.yml
  - service-dashboard.yml
  - service-proxy.yml
  - ingress-dashboard.yml