apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sagittarius.yml
  - hercules.yml
  - truenas.yml
  - portainer.yml
  - collabora.yml
  - opencloud.yml
  - wopi.yml
  - immich.yml
  - proxmox.yml