apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sagittarius.yml
  - truenas.yml
  - portainer.yml
  - collabora.yml
  - opencloud.yml
  - wopi.yml
  - immich.yml
  - jellyfin.yml
  - jellyseerr.yml
  - jellystat.yml
  - autobrr.yml
  - bazarr.yml
  - cleanuparr.yml
  - lidarr.yml
  - prowlarr.yml
  - qui.yml
  - radarr.yml
  - sonarr.yml
  - tdarr.yml
  - qbittorrent.yml
  - fileflows.yml