apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wopi
  namespace: cloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - wopi.cloud.starsystem.dev
      secretName: wopi-tls
  rules:
    - host: wopi.cloud.starsystem.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wopi
                port:
                  number: 9300