apiVersion: v1
kind: Service
metadata:
  name: wopi
  namespace: cloud
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/path: /metrics
    prometheus.io/port: "9302"
spec:
  type: ClusterIP
  selector:
    app: opencloud
    component: wopi
  ports:
    - name: http
      port: 9300
      targetPort: 9300
    - name: grpc
      port: 9301
      targetPort: 9301
    - name: metrics
      port: 9302
      targetPort: 9302