apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: users
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/scheme: http
    prometheus.io/path: /metrics
    prometheus.io/port: "9000"
spec:
  selector:
    app: keycloak
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: internal
      port: 9000
      targetPort: 9000