apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql-cluster
resources:
  - namespace.yml
  - cluster.yml
  - credentials-baserow.yml
  - credentials-gitea.yml
  - credentials-lldap.yml
  - credentials-authelia.yml
  - credentials-jellyseerr.yml
  - database-baserow.yml
  - database-gitea.yml
  - database-lldap.yml
  - database-authelia.yml
  - database-jellyseerr.yml