apiVersion: v1
kind: ConfigMap
metadata:
  name: mafl-config
data:
  config.yml: |-
    title: Dashboard

    tags:
      - name: VPN Required
        color: amber
      - name: SLUGSoc
        color: green
      - name: NoDDSoc
        color: yellow
      - name: ShefESH
        color: sky

    services:
      All:
        - title: GitHub
          description: Public Git repositories
          link: https://github.com
          icon:
            name: mdi:github
            wrap: true
          status:
            enabled: true
        - title: Google Calendar
          description: Timetabling and events
          link: https://calendar.google.com
          icon:
            name: logos:google-calendar
            wrap: true
          status:
            enabled: true
        - title: Google Drive
          description: File storage and sharing
          link: https://drive.google.com
          icon:
            name: logos:google-drive
            wrap: true
          status:
            enabled: true
        - title: Google Mail
          description: Student and society inboxes
          link: https://gmail.com
          icon:
            name: logos:google-gmail
            wrap: true
          status:
            enabled: true
        - title: YouTrack
          description: Project manager and todo list
          link: https://youtrack.starsystem.dev/agiles/189-14/current
          icon:
            name: logos:youtrack
            wrap: true
            color: "#ff6f00"
          status:
            enabled: true
      University:
        - title: Blackboard
          description: Virtual Learning Environment
          link: https://vle.shef.ac.uk/ultra/course
          icon:
            url: https://assets.jackgledhill.com/img/blackboard_circle.webp
            wrap: true
          status:
            enabled: true
        - title: ECF Form 25/26
          description: Extenuating Circumstances request form for 25/26
          link: https://docs.google.com/forms/d/e/1FAIpQLSfX_-PkxcCgpKN5qfmmtAphgTRhQRTuSnJh_oSP7-OoDbg7cQ/viewform
          icon:
            name: simple-icons:googleforms
            wrap: true
            color: #7248b9
          status:
            enabled: true
        - title: GitLab
          description: SCS Git server
          link: https://git.shefcompsci.org.uk
          icon:
            name: logos:gitlab-icon
            wrap: true
          status:
            enabled: true
        - title: Gradebook 25/26
          description: Spreadsheet of module marks
          link: https://docs.google.com/spreadsheets/d/1xzLdqVU7NeU7hceiBwX4BM50yaAvXTv1vmSMp8_UcsI/edit?usp=sharing
          icon:
            name: mdi:google-spreadsheet
            wrap: true
            color: "#22a364"
          status:
            enabled: true
        - title: iSheffield
          description: Timetable and check-in dashboard
          link: https://i.sheffield.ac.uk
          icon:
            url: https://assets.jackgledhill.com/img/uos_circle.webp
            wrap: true
          status:
            enabled: true
        - title: MUSE
          description: Student dashboard
          link: https://students.sheffield.ac.uk
          icon:
            url: https://assets.jackgledhill.com/img/uos_circle.webp
            wrap: true
          status:
            enabled: true
        - title: SCS Student Handbook
          description: Undergrad handbook for CompSci students
          link: https://students.sheffield.ac.uk/cs
          icon:
            url: https://assets.jackgledhill.com/img/uos_circle.webp
            wrap: true
          status:
            enabled: true
      Work:
        - title: Asana
          description: Project and task manager
          link: https://app.asana.com/1/316564282827695/project/1203928111011483/board/1203939006687271
          icon:
            name: logos:asana-icon
            wrap: true
          status:
            enabled: true
        - title: Figma
          description: Web design studio
          link: https://figma.com
          icon:
            name: logos:figma
            wrap: true
          status:
            enabled: true
        - title: StaffSavvy
          description: Time tracking and HR
          link: https://ssu.staffsavvy.me
          icon:
            url: https://assets.jackgledhill.com/img/staffsavvy.webp
            wrap: true
          status:
            enabled: true
        - title: SUMS
          description: SU Management System
          link: https://sh.sums.su
          icon:
            url: https://assets.jackgledhill.com/img/sums_circle.webp
            wrap: true
          status:
            enabled: true
      Societies:
        - title: NoDDSoc Verification Form
          description: Form responses for member verification
          link: https://docs.google.com/spreadsheets/d/1IahlyPkXOxhex2S-NMBtIB8KL_6nUjEm4niIvGLY5ts/edit?usp=sharing
          icon:
            name: mdi:google-spreadsheet
            wrap: true
            color: "#22a364"
          status:
            enabled: true
          tags:
            - NoDDSoc
        - title: ShefESH Session Guide
          description: Session tracker spreadsheet
          link: https://docs.google.com/spreadsheets/d/1LQSoXxezew2GnaIvHUch-pusOo0_3ApNnFt2KuCVXzQ/edit?usp=sharing
          icon:
            name: mdi:google-spreadsheet
            wrap: true
            color: "#22a364"
          status:
            enabled: true
          tags:
            - ShefESH
        - title: SU Dashboard
          description: Society dashboards
          link: https://su.sheffield.ac.uk/auth/dashboard
          icon:
            url: https://assets.jackgledhill.com/img/ssu.webp
            wrap: true
          status:
            enabled: true
        - title: Sleipnir Cockpit
          description: Management system for Sleipnir
          link: https://sleipnir.sheffield.ac.uk
          icon:
            name: simple-icons:cockpit
            wrap: true
            color: "#3464a4"
          status:
            enabled: true
          tags:
            - VPN Required
            - SLUGSoc
      Personal:
        - title: Cloudflare
          description: Domain registration & management
          link: https://dash.cloudflare.com
          icon:
            name: devicon:cloudflare
            wrap: true
          status:
            enabled: true
        - title: Constellation Dashboard
          description: Access internal services
          link: https://home.starsystem.dev
          icon:
            name: simple-icons:homarr
            wrap: true
            color: "#fa5352"
          status:
            enabled: true
        - title: Hetzner Console
          description: Manage servers and object storage
          link: https://console.hetzner.com/projects
          icon:
            name: simple-icons:hetzner
            wrap: true
            color: "#d50b2d"
          status:
            enabled: true
      Home:
        - title: Bills Spreadsheet
          description: Bills and expenses tracker
          link: https://docs.google.com/spreadsheets/d/1BrB9kMomzi2pwmT4mPRdmRQoMSzJCzJX8QjCZGWuSNU/edit?usp=sharing
          icon:
            name: mdi:google-spreadsheet
            wrap: true
            color: "#22a364"
          status:
            enabled: true
        - title: Home Router
          description: Router management for home network
          link: http://192.168.0.1
          icon:
            name: material-symbols:router
            wrap: true
          status:
            enabled: true
      Tools:
        - title: Random Passwords
          description: Generate 5 random 32-char passwords
          link: https://www.random.org/passwords/?num=5&len=32&format=html&rnd=new
          icon:
            name: mdi:secure
            wrap: true
          status:
            enabled: true