apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mafl
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
spec:
  tls:
    - hosts:
        - mafl.starsystem.dev
      secretName: mafl-tls
  rules:
    - host: mafl.starsystem.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mafl
                port:
                  number: 3000