apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow-asgi
  namespace: apps
  annotations:
    secret.reloader.stakater.com/reload: "baserow-env"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: baserow
      component: asgi
  template:
    metadata:
      labels:
        app: baserow
        component: asgi
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - baserow
                    - key: component
                      operator: In
                      values:
                        - asgi
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: baserow-asgi
          image: baserow/backend:2.0.3
          workingDir: /baserow
          args:
            - "gunicorn"
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - secretRef:
                name: baserow-env
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - curl
                - --fail
                - --silent
                - http://localhost:8000/api/_health/
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1