apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow
  namespace: apps
  annotations:
    secret.reloader.stakater.com/reload: "baserow-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baserow
  template:
    metadata:
      labels:
        app: baserow
    spec:
      containers:
        - name: baserow
          image: baserow/baserow:2.0.3
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - secretRef:
                name: baserow-env
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 4Gi
          volumeMounts:
            - name: data
              mountPath: /baserow/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: baserow-data