apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baserow
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - baserow.starsystem.dev
      secretName: baserow-web-tls
    - hosts:
        - api.baserow.starsystem.dev
      secretName: baserow-api-tls
  rules:
    - host: baserow.starsystem.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: baserow-web
                port:
                  number: 80
    - host: api.baserow.starsystem.dev
      http:
        paths:
          - path: "/ws/"
            pathType: Prefix
            backend:
              service:
                name: baserow-asgi
                port:
                  number: 80
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: baserow-wsgi
                port:
                  number: 80