apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baserow
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - baserow.starsystem.dev
      secretName: baserow-tls
  rules:
    - host: baserow.starsystem.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: baserow
                port:
                  number: 80