apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - postgres-pvc-data.yml
  - postgres-pvc-wal.yml
  - postgres-credentials.yml
  - postgres.yml
  - postgres-service.yml
  - baserow-env.yml
  - baserow-pvc.yml
  - baserow.yml
  - baserow-service.yml
  - baserow-ingress.yml