apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis-config.yml
  - redis-deployment.yml
  - redis-service.yml
  - env.yml
  - asgi-deployment.yml
  - asgi-service.yml
  - wsgi-deployment.yml
  - wsgi-service.yml
  - worker-deployment.yml
  - web-deployment.yml
  - web-service.yml
  - ingress.yml