---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: baserow-redis-config
  namespace: apps
spec:
  encryptedData:
    redis.conf: AgBwIrHOQaK6cJ76cDSNaRKSOwgql2UsIQ45/fK+eOhytmQ1Q3L6aNvmMRGvTC4M1Y4W7IRp45F2/2xmWE8MFM+y4GseK4i9KwByclriS3zrrZcNjYg8u/HIuZAKX/oyPpfFOjFr9lfLN7IKbJdfnTx+aWcrjrXg6l/4pgi9UuEHFRKH1Qhoj7XF10JFFnfjcwDNAIx2mKRJ1EfQBTWtytfOC7dNMwQFSkNlCTAoLQAaHtR4oBLdM/12rvMlIlJiW0o7jnznZL1KWKbQgExZ25TsmhG5bCoZ2JV3t5QyY1bvUhqBNXU9DsuneHqPJv2BdF1S7ngO5raVEQyMtVMDGJUOTMgrZe7XTnK1W8quH8aEBnjod63ah5CLRdyOJQ4x0B47ibf4UpA0izBm4/EyQlVg9flPPc+hLIQnirBYMjePuzqCfnd1iNgcMiOPGEONMjay1BAIZikoa1f4W0FGVp8ymg7zTK1DUuRnd8Q017DKv0Ng5eTcfvvM6/5csudoFyQVaGIXTXTllLEDQlJBfJeHoGgXWQNgEy98Qq4MK71YrE5YWxylkLCynkCiva5/z0JeMXFRWbIfjwf5ZcX8tbLmh50m+JfcP5DTEhZdCkuyrfzF96LbTF4HJsCvbCA9ioON7RAcekbDIJhPfj/wocO6HTblwNlMgfjnweVD9mFHUm3d7UuA4S8ccWKp+ROgEo3RuTzT4qNxJbNQVGdZnxcw+NO4rdnk9HHHQetgRzZTbPwY38kDQPMy2fEehaHyptivEI+KbJoNqXqWsuN4Zz643naI
  template:
    metadata:
      creationTimestamp: null
      name: baserow-redis-config
      namespace: apps
