apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow-worker
  namespace: apps
  annotations:
    secret.reloader.stakater.com/reload: "baserow-env"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baserow
      component: worker
  template:
    metadata:
      labels:
        app: baserow
        component: worker
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - baserow
                    - key: component
                      operator: In
                      values:
                        - worker
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: baserow-worker
          image: baserow/backend:2.0.3
          args:
            - "celery-worker"
          envFrom:
            - secretRef:
                name: baserow-env
          resources:
            requests:
              cpu: 150m
              memory: 1000Mi
            limits:
              memory: 1500Mi
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /baserow/backend/docker/docker-entrypoint.sh celery-worker-healthcheck
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
        - name: baserow-export-worker
          image: baserow/backend:2.0.3
          args:
            - "celery-exportworker"
          envFrom:
            - secretRef:
                name: baserow-env
          resources:
            requests:
              cpu: 150m
              memory: 1000Mi
            limits:
              memory: 1500Mi
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /baserow/backend/docker/docker-entrypoint.sh celery-exportworker-healthcheck
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 10
        - name: baserow-beat-worker
          image: baserow/backend:2.0.3
          args:
            - "celery-beat"
          resources:
            requests:
              cpu: 50m
              memory: 250Mi
            limits:
              memory: 500Mi
          envFrom:
            - secretRef:
                name: baserow-env