kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitea
  namespace: apps
  annotations:
    secret.reloader.stakater.com/reload: "gitea-env"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
      component: server
  template:
    metadata:
      labels:
        app: gitea
        component: server
    spec:
      containers:
        - name: gitea
          image: docker.io/gitea/gitea:latest
          envFrom:
            - secretRef:
                name: gitea-env
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 500Mi
          ports:
            - name: http
              containerPort: 3000
            - name: ssh
              containerPort: 2222
          volumeMounts:
            - name: config
              mountPath: /etc/gitea
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: gitea-config
        - name: data
          persistentVolumeClaim:
              claimName: gitea-data