apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - gitea-env.yml
  - gitea-pvc-config.yml
  - gitea-pvc-data.yml
  - gitea.yml
  - gitea-service-ssh.yml
  - gitea-service-web.yml
  - gitea-ingress.yml