apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - env.yml
  - pvc-config.yml
  - pvc-data.yml
  - deployment.yml
  - service-ssh.yml
  - service-web.yml
  - ingress.yml
  - add-oidc-env.yml
  - add-oidc.yml